name: 16_p16_first_block_k357
model:
  type: classifier
  strategy: classification
  backbone:
    type: mixnet_s_search
    model_name: mixnet_s
    pretrained: true
    input_size: 408
    placement: FIRST_BLOCK
    kernel_sizes:
      - 3
      - 5
      - 7
    gate_type: none
    gate_reduction: 4
  head:
    type: linear
    drop_rate: 0.0
