apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: p-wyy-black-tea-dev

resources:
  - ../../base
  - job-dry-run.yaml

images:
  - name: 10.43.250.50/black-tea-simple/black-tea-simple-data
    newTag: git-296a4b345a03

labels:
  - pairs:
      app.kubernetes.io/environment: dev
