name: lm12_cdc_b3_d123
random_seed: 2026
model:
  type: classifier
  strategy: classification
  backbone:
    type: mixnet_s_litemono
    model_name: mixnet_s
    pretrained: true
    input_size: 408
    cdc_stage_plans:
      3:
        - 1
        - 2
        - 3
  head:
    type: linear
    drop_rate: 0.0
litemono:
  group: cdc_stage
  stage: blocks_3
  dilations:
    - 1
    - 2
    - 3
