name: safnet_scratch
model:
  type: classifier
  strategy: classification
  backbone:
    type: safnet
    pretrained: false
    num_classes: 4
    reduction: 16
  head:
    type: identity
    drop_rate: 0.0
