name: msp_p5
model:
  type: classifier
  strategy: classification
  backbone:
    type: efficientnet_v2_s_multiscale_fusion
    pretrained: true
    num_classes: 4
    final_dropout: 0.2
    multiscale_type: msp
    multiscale_positions: [5]
    multiscale_fusion: concat
    neck_features: []
    neck_fusion: none
    neck_channels: 128
  head:
    type: identity
    drop_rate: 0.0
