apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: black-tea-runs
  labels:
    app.kubernetes.io/component: results
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lab-local-retain
  resources:
    requests:
      storage: 50Gi

