name: neck_concat_f3456
model:
  type: classifier
  strategy: classification
  backbone:
    type: efficientnet_v2_s_multiscale_fusion
    pretrained: true
    num_classes: 4
    final_dropout: 0.2
    multiscale_type: none
    multiscale_positions: []
    multiscale_fusion: concat
    neck_features: [3, 4, 5, 6]
    neck_fusion: concat
    neck_channels: 128
  head:
    type: identity
    drop_rate: 0.0
