name: probe_freeze_all
model:
  type: classifier
  strategy: classification
  backbone:
    type: efficientnet_v2_s_stage_probe
    pretrained: true
    output_stage: 6
    trainable_stages: []
  head:
    type: linear
    drop_rate: 0.0
