name: adamnorm_lr0p0001__13_p13_only_s3_k357
model:
  type: classifier
  strategy: classification
  backbone:
    type: mixnet_s_search
    model_name: mixnet_s
    pretrained: true
    input_size: 408
    placement: ONLY_S3
    kernel_sizes:
    - 3
    - 5
    - 7
    gate_type: none
    gate_reduction: 4
  head:
    type: linear
    drop_rate: 0.0
optimizer:
  type: adamnorm
  lr: 0.0001
  gamma: 0.95
adamnorm_source: adamnorm_stagemask_001101_k357_lr0p0001
target_source: 13_p13_only_s3_k357
target_family: structure
