name: saa_rep_baseline_seed42
random_seed: 42
model:
  type: classifier
  strategy: classification
  backbone:
    type: timm
    model_name: mixnet_s
    pretrained: true
    input_size: 408
  head: {type: linear, drop_rate: 0.0}
