name: efficientformerv2_s2_ce
model:
  type: classifier
  strategy: classification
  backbone:
    type: timm
    model_name: efficientformerv2_s2.snap_dist_in1k
    pretrained: true
  head:
    type: linear
    drop_rate: 0.0
