name: vim_small_midclstok_ce
model:
  type: classifier
  strategy: classification
  backbone:
    type: vim_small_midclstok
    num_classes: 4
    pretrained: true
    code_dir: external/Vim
    pretrained_repo: hustvl/Vim-small-midclstok
    model_builder: vim_small_patch16_224_bimambav2_final_pool_mean_abs_pos_embed_with_midclstok_div2
  head:
    type: identity
    drop_rate: 0.0
